export * from "./human";
export * from "./elephant";
export * from "./tree";
export * from "./robots/octopod";
export * from "./robots/tetrapod";
export * from "./robots/flyingBot";
export * from "./robots/ufo";
export * from "./primitives";
export * from "./sprite";
